CREATE TABLE IF NOT EXISTS agent_snapshots (
    agent_id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    role TEXT NOT NULL,
    ideology TEXT NOT NULL,
    communication_style TEXT NOT NULL,
    emotion REAL NOT NULL,
    emotion_state_json TEXT NOT NULL,
    stress REAL NOT NULL,
    expectation REAL NOT NULL,
    satisfaction REAL NOT NULL,
    dopamine_level REAL NOT NULL,
    influence_score REAL NOT NULL,
    schemas_json TEXT NOT NULL,
    schema_flexibility REAL NOT NULL,
    equilibrium_index REAL NOT NULL,
    empathy_level REAL NOT NULL,
    last_appraisal_json TEXT,
    memory_size INTEGER NOT NULL,
    state_debug_json TEXT NOT NULL
);

-- last_appraisal_json stores the compact AppraisalSummary exposed by
-- agents[].state.last_appraisal, not the full internal AppraisalRecord.
-- Deprecated compatibility columns intentionally kept here as comments only.
-- Restore these columns from state_debug_json if a downstream consumer still
-- needs the old flattened table shape:
-- performance_prediction REAL NOT NULL,
-- last_cognitive_mode TEXT NOT NULL,
-- dominant_emotion_label TEXT NOT NULL,
-- empathized_negative_emotion REAL NOT NULL,
-- dopamine_prediction_error REAL NOT NULL,
-- moral_reward REAL NOT NULL,
-- social_influence_reward REAL NOT NULL,
-- semantic_similarity REAL NOT NULL,
-- explicit_tom_triggered INTEGER NOT NULL,
-- beliefs_json TEXT NOT NULL,
-- desires_json TEXT NOT NULL,
-- intentions_json TEXT NOT NULL,
-- knowledge_json TEXT NOT NULL,
-- epsilon REAL NOT NULL,
-- zeta REAL NOT NULL,
-- coping_potential REAL NOT NULL,
-- performance REAL NOT NULL,
-- confirmation REAL NOT NULL,
-- last_contagion_pad_json TEXT NOT NULL,
-- last_contagion_vector_json TEXT NOT NULL,
-- appraisal_runtime_json TEXT NOT NULL,
-- latent_runtime_json TEXT NOT NULL,
-- action_runtime_json TEXT NOT NULL,
-- appraisal_count INTEGER NOT NULL,
